"""empty message

Revision ID: 7596f3b76083
Revises: 228b6bc0f524
Create Date: 2022-03-29 09:53:55.376923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7596f3b76083'
down_revision = '228b6bc0f524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t2id', sa.Integer(), nullable=True),
    sa.Column('field1_2', sa.VARCHAR(), nullable=True),
    sa.Column('field2_2', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['t2id'], ['test1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test2')
    # ### end Alembic commands ###
